# Documentation: http://docs.travis-ci.com/user/languages/julia/
# Example: https://github.com/JuliaLang/Example.jl
language: julia

os:
  - linux
  - osx

julia:
  - 1.3
  - 1.4
  - nightly

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false

#codecov: true

#coveralls: true
