# Documentation: http://docs.travis-ci.com/user/languages/julia/
# Example: https://github.com/JuliaLang/Example.jl
language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly

notifications:
  email: false

codecov: true

coveralls: true

#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';

matrix:
  allow_failures:
  - julia: nightly

before_script:
  - julia -e 'using Pkg;
              Pkg.add(PackageSpec(url="https://github.com/emmt/ArrayTools.jl"));
              Pkg.instanciate();'
  - julia -e 'using Pkg;
              Pkg.add(PackageSpec(url="https://github.com/emmt/LazyAlgebra.jl"));
              Pkg.instanciate();'
