# Documentation: http://docs.travis-ci.com/user/languages/julia/
# Example: https://github.com/JuliaLang/Example.jl
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly
notifications:
  email: false

## uncomment the following lines to allow failures on some specific julia
## versions (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

before_script:
  - julia -e 'using Pkg;
              Pkg.add(PackageSpec(url="https://github.com/emmt/ArrayTools.jl"));
              Pkg.add(PackageSpec(url="https://github.com/emmt/LazyAlgebra.jl"));'

after_success:
  # push coverage results to Coveralls
  - julia -e 'if VERSION >= v"0.7.0-DEV.5183"; using Pkg; end; cd(Pkg.dir("OptimPackNextGen")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'if VERSION >= v"0.7.0-DEV.5183"; using Pkg; end; cd(Pkg.dir("OptimPackNextGen")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
